//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmsManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FilmsManager.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, stay.
        /// </summary>
        internal static string AbortPickImageCancelText {
            get {
                return ResourceManager.GetString("AbortPickImageCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel selecting a picture?.
        /// </summary>
        internal static string AbortPickImageMessage {
            get {
                return ResourceManager.GetString("AbortPickImageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, abort.
        /// </summary>
        internal static string AbortPickImageOkText {
            get {
                return ResourceManager.GetString("AbortPickImageOkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort image selection?.
        /// </summary>
        internal static string AbortPickImageTitle {
            get {
                return ResourceManager.GetString("AbortPickImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string ActionGenre {
            get {
                return ResourceManager.GetString("ActionGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, stay.
        /// </summary>
        internal static string AddFilmAbortCancelButton {
            get {
                return ResourceManager.GetString("AddFilmAbortCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel adding a movie?.
        /// </summary>
        internal static string AddFilmAbortMessage {
            get {
                return ResourceManager.GetString("AddFilmAbortMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, abort.
        /// </summary>
        internal static string AddFilmAbortOkButton {
            get {
                return ResourceManager.GetString("AddFilmAbortOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort addition?.
        /// </summary>
        internal static string AddFilmAbortTitle {
            get {
                return ResourceManager.GetString("AddFilmAbortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, i want to choose one.
        /// </summary>
        internal static string AddFilmDefaultImageCancelButton {
            get {
                return ResourceManager.GetString("AddFilmDefaultImageCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to go with the default image?.
        /// </summary>
        internal static string AddFilmDefaultImageMessage {
            get {
                return ResourceManager.GetString("AddFilmDefaultImageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string AddFilmDefaultImageOkButton {
            get {
                return ResourceManager.GetString("AddFilmDefaultImageOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default image.
        /// </summary>
        internal static string AddFilmDefaultImageTitle {
            get {
                return ResourceManager.GetString("AddFilmDefaultImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Movie Title.
        /// </summary>
        internal static string AddFilmPageEntryPlaceholder {
            get {
                return ResourceManager.GetString("AddFilmPageEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Genre.
        /// </summary>
        internal static string AddFilmPagePickerPlaceholder {
            get {
                return ResourceManager.GetString("AddFilmPagePickerPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a film.
        /// </summary>
        internal static string AddFilmPageTitle {
            get {
                return ResourceManager.GetString("AddFilmPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drama.
        /// </summary>
        internal static string DramaGenre {
            get {
                return ResourceManager.GetString("DramaGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fantasy.
        /// </summary>
        internal static string FantasyGenre {
            get {
                return ResourceManager.GetString("FantasyGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film details.
        /// </summary>
        internal static string FilmDetailsPageTitle {
            get {
                return ResourceManager.GetString("FilmDetailsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uk.png.
        /// </summary>
        internal static string Flag {
            get {
                return ResourceManager.GetString("Flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        internal static string GenreColumn {
            get {
                return ResourceManager.GetString("GenreColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        internal static string GoBackButtonText {
            get {
                return ResourceManager.GetString("GoBackButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add film.
        /// </summary>
        internal static string HomePageAddButton {
            get {
                return ResourceManager.GetString("HomePageAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Films Manager.
        /// </summary>
        internal static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humour.
        /// </summary>
        internal static string HumourGenre {
            get {
                return ResourceManager.GetString("HumourGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string ImageColumn {
            get {
                return ResourceManager.GetString("ImageColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EN.
        /// </summary>
        internal static string LanguageAbreviation {
            get {
                return ResourceManager.GetString("LanguageAbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language selection.
        /// </summary>
        internal static string LanguageSelectionPageTitle {
            get {
                return ResourceManager.GetString("LanguageSelectionPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, stay.
        /// </summary>
        internal static string MissingEntriesCancelButton {
            get {
                return ResourceManager.GetString("MissingEntriesCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all values have been inerted. Abort adding film?.
        /// </summary>
        internal static string MissingEntriesMessage {
            get {
                return ResourceManager.GetString("MissingEntriesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, abort.
        /// </summary>
        internal static string MissingEntriesOkButton {
            get {
                return ResourceManager.GetString("MissingEntriesOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing entries.
        /// </summary>
        internal static string MissingEntriesTitle {
            get {
                return ResourceManager.GetString("MissingEntriesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an image.
        /// </summary>
        internal static string OpenGalleryButton {
            get {
                return ResourceManager.GetString("OpenGalleryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose from gallery.
        /// </summary>
        internal static string OpenMobileGalleryText {
            get {
                return ResourceManager.GetString("OpenMobileGalleryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick movie image.
        /// </summary>
        internal static string PickImagePageTitle {
            get {
                return ResourceManager.GetString("PickImagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preloaded images.
        /// </summary>
        internal static string PreloadedImagesText {
            get {
                return ResourceManager.GetString("PreloadedImagesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScienceFiction.
        /// </summary>
        internal static string ScienceFictionGenre {
            get {
                return ResourceManager.GetString("ScienceFictionGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select movie genre to filter by.
        /// </summary>
        internal static string SearchFilmPagePickerPlaceholder {
            get {
                return ResourceManager.GetString("SearchFilmPagePickerPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert movie title to search for.
        /// </summary>
        internal static string SearchFilmPageSearchBarPlaceholder {
            get {
                return ResourceManager.GetString("SearchFilmPageSearchBarPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search film.
        /// </summary>
        internal static string SearchFilmPageTitle {
            get {
                return ResourceManager.GetString("SearchFilmPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super heroes.
        /// </summary>
        internal static string SuperHeroesGenre {
            get {
                return ResourceManager.GetString("SuperHeroesGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terror.
        /// </summary>
        internal static string TerrorGenre {
            get {
                return ResourceManager.GetString("TerrorGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string TitleColumn {
            get {
                return ResourceManager.GetString("TitleColumn", resourceCulture);
            }
        }
    }
}
